import { StyleSheet } from 'react-native';

import { radius, shadows, spacing, typography } from '../theme/theme';

export const BACKGROUND_IMAGE =
  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop';

export const getMemberStyles = (colors) =>
  StyleSheet.create({
    lookupBackground: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    lookupOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
    },
    lookupSafe: {
      flex: 1,
    },
    lookupContainer: {
      flex: 1,
      justifyContent: 'center',
      padding: spacing.lg,
    },
    brand: {
      alignItems: 'center',
      marginBottom: spacing.xl,
    },
    logoCircle: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.3)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: spacing.sm,
      ...shadows.glow,
    },
    brandName: {
      fontSize: 32,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    brandTagline: {
      fontSize: 14,
      color: 'rgba(255, 255, 255, 0.8)',
      marginTop: 4,
    },
    lookupCard: {
      backgroundColor: colors.surface,
      padding: spacing.xl,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      ...shadows.md,
    },
    title: {
      ...typography.heading,
      fontSize: 24,
      color: colors.textPrimary,
      marginBottom: spacing.xs,
    },
    subtitle: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: spacing.xl,
    },
    errorText: {
      color: colors.danger,
      marginBottom: spacing.md,
      fontSize: 13,
      fontWeight: '600',
      backgroundColor: `${colors.danger}15`,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.sm,
      borderRadius: radius.sm,
    },
    inputGroup: {
      marginBottom: spacing.lg,
    },
    label: {
      fontSize: 12,
      color: colors.textSecondary,
      fontWeight: '700',
      marginBottom: 8,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    inputWrap: {
      height: 52,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: radius.sm,
      paddingHorizontal: spacing.md,
      backgroundColor: colors.surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    input: {
      flex: 1,
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '600',
    },
    dashboardSafe: {
      flex: 1,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    content: {
      padding: spacing.md,
      gap: spacing.md,
    },
    dashboardContent: {
      paddingTop: spacing.lg,
    },
    dashboardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
    },
    dashboardHeaderCopy: {
      flex: 1,
      minWidth: 0,
    },
    dashboardGreeting: {
      color: colors.textPrimary,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '800',
      marginTop: 2,
    },
    dashboardSubtitle: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
      marginTop: 4,
    },
    dashboardRefreshButton: {
      width: 48,
      height: 48,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
      ...shadows.sm,
    },
    dashboardHero: {
      backgroundColor: '#10231F',
      borderRadius: 30,
      padding: 20,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.08)',
      ...shadows.glow,
    },
    dashboardHeroGlow: {
      position: 'absolute',
      right: -56,
      top: -66,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: `${colors.accent}40`,
    },
    dashboardHeroTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    dashboardAvatarWrap: {
      width: 70,
      height: 70,
      borderRadius: 24,
      padding: 3,
      backgroundColor: 'rgba(255, 255, 255, 0.12)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.18)',
    },
    dashboardAvatar: {
      width: '100%',
      height: '100%',
      borderRadius: 21,
    },
    dashboardAvatarPlaceholder: {
      flex: 1,
      borderRadius: 21,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    dashboardAvatarInitial: {
      color: '#FFFFFF',
      fontSize: 26,
      fontWeight: '900',
    },
    dashboardHeroIdentity: {
      flex: 1,
      minWidth: 0,
    },
    dashboardHeroKicker: {
      color: '#A7D8CA',
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    dashboardHeroName: {
      color: '#FFFFFF',
      fontSize: 24,
      lineHeight: 30,
      fontWeight: '900',
      marginTop: 2,
    },
    dashboardCodeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 7,
    },
    dashboardCodeText: {
      color: '#DFF8EE',
      fontSize: 13,
      fontWeight: '800',
    },
    dashboardHeroStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      flexWrap: 'wrap',
      marginTop: 20,
    },
    dashboardHeroJoined: {
      color: '#B7C8C2',
      fontSize: 13,
      fontWeight: '700',
    },
    dashboardPlanBlock: {
      paddingTop: 22,
      paddingBottom: 16,
    },
    dashboardPlanLabel: {
      color: '#A7D8CA',
      fontSize: 13,
      fontWeight: '700',
    },
    dashboardPlanName: {
      color: '#FFFFFF',
      fontSize: 34,
      lineHeight: 40,
      fontWeight: '900',
      marginTop: 4,
    },
    dashboardHeroMeta: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    dashboardHeroMetaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(255, 255, 255, 0.11)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.13)',
      borderRadius: 16,
      paddingHorizontal: 12,
      paddingVertical: 10,
      maxWidth: '100%',
    },
    dashboardHeroMetaText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '800',
      flexShrink: 1,
    },
    renewalPanel: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
      ...shadows.sm,
    },
    renewalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    renewalIcon: {
      width: 48,
      height: 48,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    renewalCopy: {
      flex: 1,
      minWidth: 0,
    },
    renewalLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    renewalTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 26,
      fontWeight: '900',
      marginTop: 2,
    },
    renewalBadge: {
      borderRadius: radius.full,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 6,
      maxWidth: 138,
    },
    renewalBadgeText: {
      fontSize: 12,
      fontWeight: '900',
    },
    progressTrack: {
      height: 9,
      borderRadius: radius.full,
      backgroundColor: colors.surfaceAlt,
      overflow: 'hidden',
      marginTop: 18,
    },
    progressFill: {
      height: '100%',
      borderRadius: radius.full,
    },
    renewalFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
      marginTop: 10,
      flexWrap: 'wrap',
    },
    renewalFootnote: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    dashboardStatsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    dashboardStatCard: {
      flexGrow: 1,
      flexBasis: '47%',
      minWidth: 150,
      backgroundColor: colors.surface,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      ...shadows.sm,
    },
    dashboardStatIcon: {
      width: 42,
      height: 42,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    dashboardStatLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    dashboardStatValue: {
      color: colors.textPrimary,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '900',
      marginTop: 3,
    },
    dashboardStatDetail: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 4,
    },
    dashboardSection: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
      ...shadows.sm,
    },
    dashboardSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 14,
    },
    dashboardSectionEyebrow: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '900',
      textTransform: 'uppercase',
    },
    dashboardSectionTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 26,
      fontWeight: '900',
      marginTop: 2,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    screenKicker: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    screenTitle: {
      color: colors.textPrimary,
      fontSize: 30,
      fontWeight: '800',
      marginTop: 2,
    },
    iconButton: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    heroCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 20,
    },
    avatar: {
      width: 150,
      height: 150,
      borderRadius: 75,
      alignSelf: 'center',
      marginTop: 8,
    },
    avatarPlaceholder: {
      width: 150,
      height: 150,
      borderRadius: 75,
      alignSelf: 'center',
      marginTop: 8,
      backgroundColor: colors.surfaceAlt,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    name: {
      ...typography.heading,
      color: colors.textPrimary,
      fontSize: 33,
      textAlign: 'center',
      marginTop: spacing.md,
      marginBottom: spacing.xs,
    },
    idPill: {
      alignSelf: 'center',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 8,
      paddingHorizontal: 16,
      marginBottom: 8,
    },
    idPillLabel: {
      color: colors.textMuted,
      fontSize: 11,
      textAlign: 'center',
      fontWeight: '700',
      letterSpacing: 0.6,
    },
    idPillValue: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '800',
      textAlign: 'center',
    },
    heroStatusRow: {
      alignItems: 'center',
      gap: 8,
      marginBottom: spacing.md,
    },
    joined: {
      color: colors.textMuted,
      fontSize: 13,
      textAlign: 'center',
    },
    planRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: spacing.md,
    },
    planChipHighlight: {
      flex: 1.5,
      backgroundColor: colors.accent,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    planChipTextHighlight: {
      color: '#FFFFFF',
      fontWeight: '800',
      fontSize: 15,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    genderChip: {
      flex: 1,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    genderChipText: {
      color: colors.textSecondary,
      fontWeight: '700',
      fontSize: 14,
      letterSpacing: 0.5,
    },
    expiryCard: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 18,
      padding: 18,
      marginBottom: spacing.md,
    },
    expiryLabel: {
      color: colors.textSecondary,
      fontSize: 13,
    },
    expiryDate: {
      color: colors.textPrimary,
      fontWeight: '800',
      fontSize: 22,
      marginTop: 2,
    },
    daysBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
      gap: 6,
    },
    daysText: {
      fontSize: 13,
      fontWeight: '800',
    },
    metricActions: {
      flexDirection: 'row',
      backgroundColor: `${colors.success}10`,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: `${colors.success}30`,
      padding: 18,
      alignItems: 'center',
    },
    metricBlock: {
      flex: 1,
      alignItems: 'center',
    },
    metricDivider: {
      width: 1,
      height: 42,
      backgroundColor: colors.border,
      marginHorizontal: 12,
    },
    metricLabel: {
      color: colors.success,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 2,
      letterSpacing: 0.5,
    },
    metricValue: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: '800',
    },
    detailsCard: {
      backgroundColor: colors.surface,
      borderRadius: 26,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      gap: 12,
    },
    cardTitle: {
      color: colors.textPrimary,
      fontSize: 19,
      fontWeight: '800',
      marginBottom: 12,
    },
    bodyCopy: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 21,
      fontWeight: '600',
    },
    infoRow: {
      flexDirection: 'row',
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      alignItems: 'center',
    },
    infoIcon: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: `${colors.accent}15`,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    infoContent: {
      flex: 1,
    },
    infoLabel: {
      color: colors.textSecondary,
      fontSize: 13,
      marginBottom: 4,
      fontWeight: '500',
    },
    infoValue: {
      color: colors.textPrimary,
      fontWeight: '700',
      fontSize: 16,
    },
    paymentCountPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: `${colors.accent}14`,
      borderColor: `${colors.accent}35`,
      borderWidth: 1,
      borderRadius: radius.full,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    paymentCountText: {
      color: colors.accent,
      fontWeight: '800',
      fontSize: 12,
    },
    paymentList: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 14,
      overflow: 'hidden',
    },
    paymentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    paymentDate: {
      color: colors.textPrimary,
      fontSize: 14,
      fontWeight: '700',
    },
    paymentMeta: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 2,
    },
    paymentAmount: {
      color: colors.success,
      fontSize: 15,
      fontWeight: '800',
      marginLeft: 12,
    },
    emptyPayment: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      padding: 22,
      gap: 8,
    },
    emptyPaymentText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
    tabBarShell: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 14,
      paddingTop: 8,
      backgroundColor: `${colors.background}E8`,
    },
    tabBar: {
      minHeight: 66,
      borderRadius: 28,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 6,
      ...shadows.md,
    },
    tabItem: {
      flex: 1,
      height: 54,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      paddingHorizontal: 4,
    },
    tabItemActive: {
      backgroundColor: colors.accent,
    },
    tabLabel: {
      fontSize: 11,
      fontWeight: '800',
    },
    gridTwo: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.md,
    },
    toolCard: {
      width: '47.5%',
      minHeight: 148,
      backgroundColor: colors.surface,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      gap: 8,
    },
    toolIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: `${colors.accent}15`,
      justifyContent: 'center',
      alignItems: 'center',
    },
    toolTitle: {
      color: colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
    },
    toolBody: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
    },
    toolMetricRow: {
      flexDirection: 'row',
      gap: spacing.md,
    },
    toolMetric: {
      flex: 1,
      backgroundColor: colors.surfaceAlt,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      gap: 6,
    },
    toolMetricValue: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '800',
    },
    toolMetricLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '700',
    },
    largeIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: `${colors.accent}15`,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    settingsProfile: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
    },
    settingsAvatar: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: `${colors.accent}15`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsName: {
      color: colors.textPrimary,
      fontSize: 18,
      fontWeight: '800',
    },
    settingsCode: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 3,
    },
    settingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    settingIcon: {
      width: 46,
      height: 46,
      borderRadius: 23,
      backgroundColor: `${colors.accent}15`,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingCopy: {
      flex: 1,
    },
    settingTitle: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '800',
    },
    settingBody: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 2,
    },
    logoutAction: {
      height: 54,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: `${colors.danger}45`,
      backgroundColor: `${colors.danger}10`,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    logoutActionText: {
      color: colors.danger,
      fontSize: 16,
      fontWeight: '800',
    },
  });
